name: Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        include:
          - os: ubuntu-latest
            artifact_name: mmproxy
            asset_name: mmproxy-linux-amd64

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Git Submodules
        run: |
          git submodule update --init --recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake build-essential clang libtool curl

      - name: Build mmproxy
        run: |
          make BUILD=release CC=clang
          strip mmproxy

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.asset_name }}
          path: mmproxy

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Download artifacts
        uses: actions/download-artifact@v7
        with:
          path: ./artifacts

      - name: Display structure of downloaded files
        run: ls -R ./artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            ./artifacts/mmproxy-linux-amd64/mmproxy
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
